# Required Metadata
sonar.projectKey=TAPI:devops-api
sonar.projectName=Devops API

# Source & Test paths
sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Tell Sonar the project is in Python
sonar.language=py

# Point to the reports pytest generates
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-report.xml
