when:
  - event: [push, manual, tag]
    branch: master


steps:
# ========================================== TESTING V1 Version ==============================================================
# - name: Test V1
#   image: harbor.app.com/devops-infra/generic-python39:1.0.0
#   environment:
#     AWX_TOKEN:
#       from_secret: awx_token
#     CERT_CONTENT:
#       from_secret: cert_path
#     REQUESTS_CA_BUNDLE: /etc/ssl/ca.cert
#   commands:
#   - echo "$CERT_CONTENT" > /etc/ssl/ca.cert
#   - pip install -r requirements.txt
#   - pytest tests/v1 -v
#   depends_on: []

# ========================================== TESTING V2 Version ==============================================================
# - name: Test V2
#   image: harbor.app.com/devops-infra/generic-python39:1.0.0
#   environment:
#     AWX_TOKEN:
#       from_secret: awx_token
#     CERT_CONTENT:
#       from_secret: cert_path
#     REQUESTS_CA_BUNDLE: /etc/ssl/ca.cert
#   commands:
#   - echo "$CERT_CONTENT" > /etc/ssl/ca.cert
#   - pip install -r requirements.txt
#   - pytest tests/v2 -v

# ========================================== RUN SONAR SCAN ==============================================================
# - name: SonarQube
#   image: artifactory.app.com/woodpecker/plugins/sonarqube:latest 
#   settings:
#     sonar_host: https://tashtiot.sonarqube.app.com
#     sonar_token:
#       from_secret: sonar_token
#     sonar_project: TAPI:example-api


# ========================================== BUILD & PUSH ==============================================================
- name: Build image and push
  image: artifactory.app.com/woodpecker/plugins/kaniko:latest
  settings:
    registry: artifactory.app.com
    username: svc_dev_admin
    password:
      from_secret: artifactory_token
    repo: docker-dev-local/example-api
    tags: ${CI_COMMIT_TAG}
  # depends_on: [SonarQube, Test V1, Test V2]
  when:
    event: tag