sonar.projectKey=TAPI:DEVOPS-API
sonar.projectName=Devops API

sonar.sources=src/main/java
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.language=py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-report.xml